{{- if .Values.traefik.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ .Release.Name }}-httproute"
  namespace: "{{ .Release.Namespace }}"
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    sectionName: web
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "{{ .Values.traefik.path }}"
    backendRefs:
    - name: "{{ .Release.Name }}"
      namespace: "{{ .Release.Namespace }}"
      port: {{ .Values.traefik.port }}
    {{- if .Values.traefik.stripPrefix }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: "{{ .Release.Name }}-stripprefix"
    {{- end }}
{{- if .Values.traefik.stripPrefix }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: "{{ .Release.Name }}-stripprefix"
  namespace: "{{ .Release.Namespace }}"
spec:
  stripPrefix:
    prefixes:
      - "{{ .Values.traefik.path }}"
{{- end }}
{{- end }}
