{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-pv"
  labels:
    app: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: "{{ .Release.Name }}-pvc"
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
{{- end }}
